# Generated by Django 4.0.5 on 2022-06-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_header', models.CharField(default='About Me', max_length=50)),
                ('title_subheader', models.CharField(default='This is what we do', max_length=50)),
                ('team1', models.TextField()),
                ('team2', models.TextField()),
            ],
        ),
    ]
