# Generated by Django 4.0.5 on 2022-06-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.TextField()),
                ('team2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='/', max_length=50)),
                ('github', models.CharField(default='www.github.com', max_length=250)),
                ('profession', models.CharField(default='/', max_length=250)),
                ('img', models.ImageField(upload_to='teams')),
            ],
        ),
    ]
