# Generated by Django 4.0.5 on 2022-06-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_title_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='/', max_length=50)),
                ('github', models.CharField(default='www.github.com', max_length=250)),
                ('profession', models.CharField(default='/', max_length=250)),
                ('img', models.ImageField(upload_to='teams')),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_header',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_subheader',
        ),
    ]
