# Generated by Django 4.0.6 on 2022-07-19 18:55

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='members',
            name='name',
        ),
        migrations.RemoveField(
            model_name='members',
            name='profession',
        ),
        migrations.CreateModel(
            name='MembersTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('profession', models.CharField(default='/', max_length=250)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about.members')),
            ],
            options={
                'verbose_name': 'members Translation',
                'db_table': 'about_members_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='AboutTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('page_header', models.CharField(max_length=200)),
                ('page_subheader', models.CharField(max_length=200)),
                ('team1', models.TextField()),
                ('team2', models.TextField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about.about')),
            ],
            options={
                'verbose_name': 'about Translation',
                'db_table': 'about_about_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
