# Generated by Django 4.0.6 on 2022-07-15 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_about_team1_remove_about_team2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberstranslation',
            name='github',
        ),
        migrations.RemoveField(
            model_name='memberstranslation',
            name='img',
        ),
        migrations.RemoveField(
            model_name='memberstranslation',
            name='name',
        ),
        migrations.AddField(
            model_name='members',
            name='github',
            field=models.CharField(default='www.github.com', max_length=250),
        ),
        migrations.AddField(
            model_name='members',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='teams'),
            preserve_default=False,
        ),
    ]
