# Generated by Django 4.0.5 on 2022-06-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_created_on_profile_updated_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
